local_backend: true 

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master) 
  commit_messages:
    update: Update {{collection}} “{{slug}}”

media_folder: "./assets/images/uploads" 

collections:
  - label: "Settings" 
    name: "settings" 
    allow_add: false 
    collapsed: false 
    files:
      - 
        label: "Status"
        name: "status"
        file: "_settings/status.md"  
        fields: 
          - 
            label: "Status" 
            name: "value" 
            widget: "select" 
            options: 
              - 
                label: "Латето я няма" 
                value: 1  
              - 
                label: "Латето е тук" 
                value: 2 
      - 
        label: "Status Text" 
        name: "status_text" 
        file: "_settings/status_text.md" 
        fields: 
          - 
            label: "Съобщение, когато Латето я няма" 
            name: "positive" 
            widget: "string" 
          - 
            label: "Съобщение, когато Латето е тук" 
            name: "negative" 
            widget: "string" 
        default: 
          - 
            positive: "Няма я" 
            negative: "Тук е" 
