local_backend: true 

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master) 
  commit_messages:
    update: Update {{collection}} “{{slug}}”

media_folder: "./assets/images/uploads" 

collections:
  - label: "Settings" 
    name: "settings"
    files:
      - label: "Settings"
        name: "settings"
        file: "_settings/settings.md"  
        fields: 
          - 
            label: "Status" 
            name: "status" 
            widget: "select" 
            options: 
              - 
                label: "Латето я няма" 
                value: 1  
              - 
                label: "Латето е тук" 
                value: 2 
          - 
            label: "Status Text" 
            name: "status_text" 
            allow_add: false 
            collapsed: false 
            widget: "object"  
            fields: 
              - 
                label: "Съобщение, когато Латето я няма" 
                name: "positive" 
                widget: "string" 
              - 
                label: "Съобщение, когато Латето е тук" 
                name: "negative" 
                widget: "string" 
            default: 
              - 
                positive: "Няма я" 
                negative: "Тук е" 
